### ISSUE TITLE
[production/AQM.v7] Revision required for the UFS SRW rocoto workflow

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#794] opened 2023-05-11 20:36 UTC
I received an email from NCO yesterday, which expressed concern that rocoto workflow related tasks (specifically, FV3LAM_wflow) were contributing to the degradation of performance on the WCOSS2 system. During today's meeting with NCO, the following suggestions were discussed to enhance the UFS SRW workflow.

(1) To prevent production slowdown and instability of the supercomputer, loading modules for each job should be done on the computing nodes instead of the login nodes. Loading all modules on a login node can result in multiple instances of module load activity on the node, requiring the system to do a work path tree to identify module information in the file system. The proposed solution can be found on Slide one of Lin Gan's presentation ([here](https://docs.google.com/presentation/d/1C0CuhMuIwiZqi2tA28rOwkf8SOadWBYMVL7d0HcqQgA/edit#slide=id.p)).

(2) Each job should load only the necessary modules as required, rather than loading all modules at once.

(3) The current cron job is set to run every 3 minutes in crontab list. It should be changed to an appropriate timing that is less frequent.

**Comment by chan-hoo** [comment] 2023-05-12 12:55
@JianpingHuang-NOAA, For (2), this was fixed in the 'production/AQM.v7' branch long time ago. Please update your branch with the latest one. For (3), that (`CRON_RELAUNCH_INTVL_MNTS: 3`)
 is the default setting. You don't have to use it. You can change it in `config.yaml`. For (1), @danielabdi-noaa, do you have any idea to fix this?

**Comment by danielabdi-noaa** [comment] 2023-05-12 14:57
@chan-hoo I haven't gone through the slide carefully, but I believe each task uses `$USHdir/load_module_run_task.sh` (not `$USHdir/load_module_wflow.sh`) to load the module file it needs for running the specific task. These modules are definitely loaded on the compute node as you can tell from the inclusion of this script in the last line of rocoto-generated batch script
```Bash
{{ 
#! /bin/sh
#SBATCH --account=zrtrr
#SBATCH -o /scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/../nco_dirs/output/20190701/get_extrn_lbcs_mem000_2019070100.id_1682962913.log
#SBATCH --mem=2048
#SBATCH --nodes=1-1
#SBATCH --tasks-per-node=1
#SBATCH --partition=service
#SBATCH --qos=batch
#SBATCH -t 00:45:00
#SBATCH --job-name=get_extrn_lbcs_mem000
#SBATCH --export=NONE
#SBATCH --comment=73f458df8f6c511fee648134393cd09f
export GLOBAL_VAR_DEFNS_FP='/scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta/var_defns.sh'
export USHdir='/scratch2/BMC/gsd-hpcs/Daniel.Abdi/ufs-srweather-app/ush'
export PDY='20190701'
export cyc='00'
export subcyc='00'
export LOGDIR='/scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/../nco_dirs/output/20190701'
export SLASH_ENSMEM_SUBDIR='/'
export ENSMEM_INDX='000'
export ICS_OR_LBCS='LBCS'
export EXTRN_MDL_NAME='FV3GFS'
export BOUNDARY_LEN='0'
export GEFS_INPUT_SUBDIR='#subdirGE#'
export GDASENKF_INPUT_SUBDIR='#subdirGDAS#'
export GDAS_MEM_NAME='#memNameGDAS#'
export nprocs='1'
/scratch2/BMC/gsd-hpcs/Daniel.Abdi/ufs-srweather-app/ush/load_modules_run_task.sh "get_extrn_lbcs" "/scratch2/BMC/gsd-hpcs/Daniel.Abdi/ufs-srweather-app/jobs/JREGIONAL_GET_EXTRN_MDL_FILES"
}}
```
On the other hand, the `$USHdir/load_module_wflow.sh` is used only for activating conda (incase of wcoss2 python libs I suppose) for generating workflow, so it must be loaded on the login node for the user to generate workflows there.

**Comment by chan-hoo** [comment] 2023-05-15 11:18
@JianpingHuang-NOAA, I looked through @lgannoaa's slide and found that his slide is **incorrect.** As @danielabdi-noaa mentioned above, the necessary modules are loaded by the file "ush/load_modules_run_task.sh" (NOT "ush/load_modules_wflow.sh"). The call for the file can be found in the rocoto XML file as follows (LOAD_MODULES_RUN_TASK_FP=>ush/load_modules_**run_task**.sh):
```
  <task name="nexus_gfs_sfc" cycledefs="forecast" maxtries="2" >
    <account>&ACCOUNT;</account>
    <native>-l place=excl</native>
    <nodes>1:ppn=1</nodes>
    <nodesize>&NCORES_PER_NODE;</nodesize>
    <queue>&QUEUE_DEFAULT;</queue>
    <walltime>00:30:00</walltime>
    <command>&LOAD_MODULES_RUN_TASK_FP; "nexus_gfs_sfc" "&JOBSdir;/JREGIONAL_NEXUS_GFS_SFC"</command>
```
As you can see, the file "load_modules_**wflow**.sh" doesn't load any modules except for the python environment.
```
WFLOW_MOD_FN="wflow_${machine}"
source "${HOMEdir}/etc/lmod-setup.sh" ${machine}
module use "${HOMEdir}/modulefiles"
module load "${WFLOW_MOD_FN}" > /dev/null 2>&1 || { echo "ERROR:
```
- "wflow_wcoss2":
```
load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("python", os.getenv("python_ver")))
```

Who mentioned this from NCO?
If this was a comment by NCO, it should not be caused by 1).
If this was @lgannoaa's comment in the meeting, please let him know that this is not correct.

**Closed as completed** 2023-06-22 19:48 UTC
Labels: enhancement
